version: '3.7'

services:
  postgres:
    image: postgres:11.5
    ports:
      - "5432:5432"
    env_file: .env.dev
  web:
    build: ./live-twitter-map/
    expose: 
      - 8000
    volumes:
      - ./live-twitter-map/:/app/
    entrypoint: ./check_db.sh
    command: bash entrypoint-dev.sh
    ports:
      - 8000:8000
    env_file: .env.dev
    depends_on: 
      - "redis"
      - postgres
  celery:
    build: ./live-twitter-map/
    command: celery -A tweets worker --uid=nobody --gid=nogroup --loglevel=warning -E
    depends_on:
      - "redis"
      - postgres
    env_file:
      - .env.dev
    environment:
      ENVIRONMENT: prod
      REDIS_HOST: redis
    volumes:
    - ./live-twitter-map/:/app/
  cron:
    build: ./live-twitter-map/
    command: celery -A tweets beat
    depends_on:
      - "redis"
      - postgres
    environment:
      ENVIRONMENT: prod
      REDIS_HOST: redis
    volumes:
    - ./live-twitter-map/:/app/
  tweets:
    build: ./live-twitter-map/
    command: python tweet_stream.py
    volumes:
    - ./live-twitter-map/:/app/
    depends_on:
    - postgres
    restart: on-failure
    env_file: .env.dev
  redis:
    image: redis:latest
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - web
  frontend:
    build:
      context: ./frontend
    depends_on: 
      - web
    volumes:
      - ./frontend/:/frontend/:rw
      - ./frontend/node_modules
    ports: 
      - 8080:8080
    environment: 
      - CHOKIDAR_USEPOLLING=true
