version: '3.7'

services:
  web:
    build: ./live-twitter-map/
    expose: 
      - 8000
    volumes:
      - ./live-twitter-map/:/app/
    command: bash entrypoint.sh
    ports:
      - 8000:8000
    environment:
      HELLO_WORLD: "Hello, World!"
      REDIS_HOST: "redis"
  redis:
    image: redis:latest
