# Generated by Django 3.0.7 on 2021-01-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('tweet_id', models.BigIntegerField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('timestamp_ms', models.BigIntegerField()),
                ('html', models.TextField()),
            ],
            options={
                'db_table': 'tweets',
            },
        ),
    ]
