# Generated by Django 3.0.7 on 2021-02-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='html',
            field=models.TextField(null=True),
        ),
    ]
