# Generated by Django 3.1.6 on 2021-02-23 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app')
    ]

    operations = [
    ]
