version: '3.7'

services:
  redis:
    image: redis
  web:
    build: .
    command: /bin/bash ./docker-entrypoint.sh
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - "redis"
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    environment:
      ENVIRONMENT: prod
      REDIS_HOST: redis
  celery:
    build: .
    command: celery -A tweets worker --uid=nobody --gid=nogroup --loglevel=warning -E
    depends_on:
      - "redis"
    env_file:
      - .env.dev
    environment:
      ENVIRONMENT: prod
      REDIS_HOST: redis
  cron:
    build: .
    command: celery -A tweets beat
    depends_on:
      - "redis"
    environment:
      ENVIRONMENT: prod
      REDIS_HOST: redis
      